image: zazukoians/node-java-jena
before_script:
  - npm install

stages:
  - build

pipeline_build:
  stage: build
  script:
    - npm run start
#    - npm run clean-nt
  artifacts:
    paths:
      - target/everything.nt
    expire_in: 1 day
  # except:
  #   variables:
  #       - $CRON

# tierseuchen_staging:
#   stage: staging
#   script:
#     - npm run clean-nt
#   only:
#     variables:
#         - $CRON

