image: zazukoians/node-java-jena:3.13.1
before_script:
  - npm install
  - mkdir -p target

stages:
  - build

pipeline_build_prod:
  tags:
    - medium
  stage: build
  environment:
    name: TEST
  script:
    - npm run animalpest-pipeline
    - ./scripts/put.sh

pipeline_build_int:
  tags:
    - medium
  stage: build
  environment:
    name: INT
  script:
    - npm run animalpest-pipeline
