image: zazukoians/node-java-jena:3.13.1
before_script:
  - npm install

stages:
  - build

pipeline_build:
  tags:
    - medium
  stage: build
  environment:
    name: TEST
  script:
    - npm run animalpest-pipeline-file
    - ./scripts/put.sh

