image: zazukoians/node-java-jena
before_script:
# SSH Key Setup, see https://docs.gitlab.com/ee/ci/ssh_keys/
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
# end SSH
  - npm install
#  - curl https://ipinfo.io/ip

stages:
  - build

pipeline_build:
  stage: build
  script:
    - npm run animalpest-pipeline-test
  #artifacts:
  #  paths:
  #    - target/everything.nt
  #  expire_in: 1 day
  # except:
  #   variables:
  #       - $CRON

# tierseuchen_staging:
#   stage: staging
#   script:
#     - npm run clean-nt
#   only:
#     variables:
#         - $CRON

