image: zazukoians/node-java-jena
before_script:
# SSH Key Setup, see https://docs.gitlab.com/ee/ci/ssh_keys/
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
# end SSH
  - sftp isceco-pr@sftp.zazukoians.org:upload/InfoSM.zip .
  - npm install

stages:
  - build

pipeline_build:
  stage: build
  script:
    - npm run animalpest-pipeline-test

