image: zazukoians/node-java-jena:3.13.1
before_script:
# SSH Key Setup, see https://docs.gitlab.com/ee/ci/ssh_keys/
  # - eval $(ssh-agent -s)
  # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  # - mkdir -m 700 -p ~/.ssh
  # - echo "sftp.zazukoians.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICQreGG5LpFFP/aOow7i3IGIYF4xq+6dYocwZTgawmIa" > ~/.ssh/known_hosts
  # - ls ~/.ssh
# end SSH
  - npm install

stages:
  - build

pipeline_build:
  stage: build
  script:
    - npm run animalpest-pipeline-test
    - ./scripts/put.sh

